# Generated by Django 6.1 on 2026-08-16 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150, unique=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('location', models.CharField(default='Bengaluru, India', max_length=100)),
                ('industry', models.CharField(choices=[('FinTech', 'Financial Technology & Banking'), ('SaaS', 'Enterprise SaaS & Cloud Software'), ('E-Commerce', 'E-Commerce & Retail Tech'), ('AI_Cloud', 'AI & Cloud Infrastructure'), ('EdTech', 'Education Technology'), ('HealthTech', 'Healthcare & Life Sciences'), ('Consulting', 'IT Services & Consulting'), ('Logistics', 'Supply Chain & Logistics Tech'), ('Cybersecurity', 'Cybersecurity & InfoSec')], db_index=True, default='SaaS', max_length=50)),
                ('company_size', models.CharField(default='500-1000 employees', max_length=50)),
                ('logo_color', models.CharField(default='indigo', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('rating', models.FloatField(default=4.2)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('category', models.CharField(choices=[('programming', 'Programming Languages'), ('database', 'Databases & Warehousing'), ('visualization', 'Visualization & BI'), ('analytics', 'Analytics & Statistics'), ('cloud_devops', 'Cloud & DevOps'), ('ai_ml', 'AI & Machine Learning'), ('web_mobile', 'Web & Frameworks'), ('tools_other', 'Tools & Methodologies')], db_index=True, default='programming', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, default='fa-solid fa-code', max_length=50)),
                ('importance_weight', models.FloatField(default=1.0)),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('role_category', models.CharField(choices=[('Data Analyst', 'Data Analyst'), ('Data Scientist', 'Data Scientist'), ('Business Intelligence Analyst', 'Business Intelligence Analyst'), ('Machine Learning Engineer', 'Machine Learning Engineer'), ('Data Engineer', 'Data Engineer'), ('Full Stack Developer', 'Full Stack Developer'), ('Frontend Developer', 'Frontend Developer'), ('Backend Developer', 'Backend Developer'), ('DevOps Engineer', 'DevOps Engineer'), ('Cloud Architect', 'Cloud Architect'), ('Cybersecurity Analyst', 'Cybersecurity Analyst'), ('Product Manager', 'Product Manager'), ('AI Research Engineer', 'AI Research Engineer'), ('Database Administrator', 'Database Administrator'), ('QA Automation Engineer', 'QA Automation Engineer')], db_index=True, max_length=100)),
                ('location', models.CharField(db_index=True, max_length=100)),
                ('experience_level', models.CharField(choices=[('Entry Level', 'Entry Level (0-2 years)'), ('Mid Level', 'Mid Level (3-5 years)'), ('Senior Level', 'Senior Level (6-9 years)'), ('Lead / Principal', 'Lead / Principal (10+ years)')], db_index=True, max_length=50)),
                ('experience_min', models.IntegerField(default=0)),
                ('experience_max', models.IntegerField(default=2)),
                ('employment_type', models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Contract', 'Contract'), ('Internship', 'Internship')], default='Full Time', max_length=50)),
                ('work_mode', models.CharField(choices=[('Remote', 'Remote'), ('Hybrid', 'Hybrid'), ('On-site', 'On-site')], db_index=True, default='Hybrid', max_length=50)),
                ('salary_min', models.FloatField(help_text='Minimum Salary in LPA')),
                ('salary_max', models.FloatField(help_text='Maximum Salary in LPA')),
                ('salary_avg', models.FloatField(db_index=True, help_text='Average Salary in LPA')),
                ('description', models.TextField()),
                ('responsibilities', models.TextField(blank=True, null=True)),
                ('requirements', models.TextField(blank=True, null=True)),
                ('benefits', models.TextField(blank=True, null=True)),
                ('posted_date', models.DateField(db_index=True)),
                ('is_active', models.BooleanField(default=True)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='jobs.company')),
                ('skills', models.ManyToManyField(blank=True, related_name='jobs', to='jobs.skill')),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
                'ordering': ['-posted_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SavedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_users', to='jobs.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-saved_at'],
                'unique_together': {('user', 'job')},
            },
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['role_category', 'location'], name='jobs_job_role_ca_9f1699_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['salary_avg', 'experience_level'], name='jobs_job_salary__c7273d_idx'),
        ),
    ]
