# Generated by Django 6.1 on 2026-08-16 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(blank=True, default='Data & Tech Professional', max_length=200)),
                ('target_role', models.CharField(default='Data Analyst', max_length=100)),
                ('education', models.CharField(choices=[("Bachelor's Degree", "Bachelor's Degree (B.Tech / BCA / B.Sc / BE)"), ("Master's Degree", "Master's Degree (M.Tech / MCA / M.Sc / MS)"), ('MBA', 'Master of Business Administration (MBA)'), ('Doctorate / PhD', 'Doctorate / PhD'), ('Diploma / Associate', 'Diploma / Associate Degree'), ('Self-Taught / Bootcamp', 'Self-Taught / Bootcamp Graduate')], default="Bachelor's Degree", max_length=100)),
                ('years_of_experience', models.FloatField(default=1.0)),
                ('current_salary', models.FloatField(blank=True, help_text='Current CTC in LPA', null=True)),
                ('expected_salary', models.FloatField(blank=True, help_text='Expected CTC in LPA', null=True)),
                ('preferred_location', models.CharField(default='Bengaluru', max_length=100)),
                ('preferred_work_mode', models.CharField(choices=[('Any', 'Any Work Mode'), ('Remote', 'Remote Only'), ('Hybrid', 'Hybrid Preferred'), ('On-site', 'On-site Preferred')], default='Any', max_length=50)),
                ('bio', models.TextField(blank=True, default='Passionate about data-driven decision making and solving complex problems.')),
                ('github_url', models.URLField(blank=True, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proficiency', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced'), ('Expert', 'Expert')], default='Intermediate', max_length=50)),
                ('years_practiced', models.FloatField(default=1.0)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_skills', to='jobs.skill')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_skills', to='accounts.userprofile')),
            ],
            options={
                'ordering': ['skill__name'],
                'unique_together': {('user_profile', 'skill')},
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='user_profiles', through='accounts.UserSkill', to='jobs.skill'),
        ),
    ]
